options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/jon-backend/varshitha-backend/click4news-backend:$SHORT_SHA'
      - '.'

  # 2. 推到 Artifact Registry（已存在的仓库）
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/jon-backend/varshitha-backend/click4news-backend:$SHORT_SHA'

  # 3. 部署到 Cloud Run（4 vCPU + 16 GiB）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'varshitha'
      - '--image'
      - 'us-east1-docker.pkg.dev/jon-backend/varshitha-backend/click4news-backend:$SHORT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--cpu'
      - '4'
      - '--memory'
      - '16Gi'
      - '--timeout'
      - '600s'
      - '--update-secrets'
      - 'MONGO_URI=mongo-uri:latest'

images:
  - 'us-east1-docker.pkg.dev/jon-backend/varshitha-backend/click4news-backend:$SHORT_SHA'
